# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'browser.ui'
#
# Created: Sun Aug 17 19:51:55 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1308, 789)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitter_4 = QtGui.QSplitter(self.centralwidget)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.splitter_2 = QtGui.QSplitter(self.splitter_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.dirTree = QtGui.QTreeView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dirTree.sizePolicy().hasHeightForWidth())
        self.dirTree.setSizePolicy(sizePolicy)
        self.dirTree.setMinimumSize(QtCore.QSize(0, 0))
        self.dirTree.setObjectName(_fromUtf8("dirTree"))
        self.hdfTree = h5TreeWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hdfTree.sizePolicy().hasHeightForWidth())
        self.hdfTree.setSizePolicy(sizePolicy)
        self.hdfTree.setMinimumSize(QtCore.QSize(0, 0))
        self.hdfTree.setAcceptDrops(True)
        self.hdfTree.setDragEnabled(True)
        self.hdfTree.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.hdfTree.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.hdfTree.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.hdfTree.setObjectName(_fromUtf8("hdfTree"))
        self.hdfTree.headerItem().setText(0, _fromUtf8("1"))
        self.dataPlotWidget = matplotlibWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataPlotWidget.sizePolicy().hasHeightForWidth())
        self.dataPlotWidget.setSizePolicy(sizePolicy)
        self.dataPlotWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.dataPlotWidget.setObjectName(_fromUtf8("dataPlotWidget"))
        self.tabWidget = QtGui.QTabWidget(self.splitter_4)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.plotsWidget = matplotlibWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotsWidget.sizePolicy().hasHeightForWidth())
        self.plotsWidget.setSizePolicy(sizePolicy)
        self.plotsWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.plotsWidget.setObjectName(_fromUtf8("plotsWidget"))
        self.gridLayout.addWidget(self.plotsWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.dataTableWidget = QtGui.QTableWidget(self.tab_2)
        self.dataTableWidget.setDragEnabled(True)
        self.dataTableWidget.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.dataTableWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.dataTableWidget.setAlternatingRowColors(True)
        self.dataTableWidget.setObjectName(_fromUtf8("dataTableWidget"))
        self.dataTableWidget.setColumnCount(0)
        self.dataTableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.dataTableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.splitter_3 = QtGui.QSplitter(self.splitter_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_3.sizePolicy().hasHeightForWidth())
        self.splitter_3.setSizePolicy(sizePolicy)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.workingTree = h5TreeWidget(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workingTree.sizePolicy().hasHeightForWidth())
        self.workingTree.setSizePolicy(sizePolicy)
        self.workingTree.setMinimumSize(QtCore.QSize(0, 0))
        self.workingTree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.workingTree.setAcceptDrops(True)
        self.workingTree.setDragEnabled(True)
        self.workingTree.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.workingTree.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.workingTree.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.workingTree.setObjectName(_fromUtf8("workingTree"))
        self.workingTree.headerItem().setText(0, _fromUtf8("1"))
        self.propsTableWidget = QtGui.QTableWidget(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propsTableWidget.sizePolicy().hasHeightForWidth())
        self.propsTableWidget.setSizePolicy(sizePolicy)
        self.propsTableWidget.setRowCount(0)
        self.propsTableWidget.setColumnCount(0)
        self.propsTableWidget.setObjectName(_fromUtf8("propsTableWidget"))
        self.propsTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.propsTableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.splitter_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoadData = QtGui.QAction(MainWindow)
        self.actionLoadData.setObjectName(_fromUtf8("actionLoadData"))
        self.actionNewFile = QtGui.QAction(MainWindow)
        self.actionNewFile.setObjectName(_fromUtf8("actionNewFile"))
        self.actionSaveFile = QtGui.QAction(MainWindow)
        self.actionSaveFile.setObjectName(_fromUtf8("actionSaveFile"))
        self.actionAddRootGroup = QtGui.QAction(MainWindow)
        self.actionAddRootGroup.setObjectName(_fromUtf8("actionAddRootGroup"))
        self.actionAddChildGroup = QtGui.QAction(MainWindow)
        self.actionAddChildGroup.setObjectName(_fromUtf8("actionAddChildGroup"))
        self.actionAddDataset = QtGui.QAction(MainWindow)
        self.actionAddDataset.setObjectName(_fromUtf8("actionAddDataset"))
        self.actionRenameTreeItem = QtGui.QAction(MainWindow)
        self.actionRenameTreeItem.setObjectName(_fromUtf8("actionRenameTreeItem"))
        self.actionRemoveTreeItem = QtGui.QAction(MainWindow)
        self.actionRemoveTreeItem.setObjectName(_fromUtf8("actionRemoveTreeItem"))
        self.actionPlotData = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/pencil29.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlotData.setIcon(icon)
        self.actionPlotData.setObjectName(_fromUtf8("actionPlotData"))
        self.actionShowCursors = QtGui.QAction(MainWindow)
        self.actionShowCursors.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/push7.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowCursors.setIcon(icon1)
        self.actionShowCursors.setObjectName(_fromUtf8("actionShowCursors"))
        self.actionSaveFileAs = QtGui.QAction(MainWindow)
        self.actionSaveFileAs.setObjectName(_fromUtf8("actionSaveFileAs"))
        self.actionZoomOut = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/home107.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomOut.setIcon(icon2)
        self.actionZoomOut.setObjectName(_fromUtf8("actionZoomOut"))
        self.actionBaseline = QtGui.QAction(MainWindow)
        self.actionBaseline.setObjectName(_fromUtf8("actionBaseline"))
        self.actionAverage = QtGui.QAction(MainWindow)
        self.actionAverage.setObjectName(_fromUtf8("actionAverage"))
        self.actionStats = QtGui.QAction(MainWindow)
        self.actionStats.setObjectName(_fromUtf8("actionStats"))
        self.actionShowInTable = QtGui.QAction(MainWindow)
        self.actionShowInTable.setObjectName(_fromUtf8("actionShowInTable"))
        self.toolBar.addAction(self.actionNewFile)
        self.toolBar.addAction(self.actionLoadData)
        self.toolBar.addAction(self.actionSaveFile)
        self.toolBar.addAction(self.actionSaveFileAs)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "NeuroDAQ Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Table", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadData.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadData.setToolTip(QtGui.QApplication.translate("MainWindow", "Load data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewFile.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewFile.setToolTip(QtGui.QApplication.translate("MainWindow", "New File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveFile.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddRootGroup.setText(QtGui.QApplication.translate("MainWindow", "Add Root Group", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddChildGroup.setText(QtGui.QApplication.translate("MainWindow", "Add Child Group", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddDataset.setText(QtGui.QApplication.translate("MainWindow", "Add Dataset", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRenameTreeItem.setText(QtGui.QApplication.translate("MainWindow", "Rename", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveTreeItem.setText(QtGui.QApplication.translate("MainWindow", "Remove Item", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlotData.setText(QtGui.QApplication.translate("MainWindow", "plotData", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlotData.setToolTip(QtGui.QApplication.translate("MainWindow", "Plot Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowCursors.setText(QtGui.QApplication.translate("MainWindow", "showCursors", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowCursors.setToolTip(QtGui.QApplication.translate("MainWindow", "Show Cursors", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveFileAs.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOut.setText(QtGui.QApplication.translate("MainWindow", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOut.setToolTip(QtGui.QApplication.translate("MainWindow", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBaseline.setText(QtGui.QApplication.translate("MainWindow", "Baseline", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBaseline.setToolTip(QtGui.QApplication.translate("MainWindow", "Baseline traces", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAverage.setText(QtGui.QApplication.translate("MainWindow", "Average", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAverage.setToolTip(QtGui.QApplication.translate("MainWindow", "Make Average", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStats.setText(QtGui.QApplication.translate("MainWindow", "Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStats.setToolTip(QtGui.QApplication.translate("MainWindow", "Measure Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowInTable.setText(QtGui.QApplication.translate("MainWindow", "Show in Table", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidgetFile import matplotlibWidget
from h5TreeWidgetFile import h5TreeWidget
